name: Super Important Workflow 

on:
  pull_request_target:
    branches: [ main ]

jobs:
  super-important-workflow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: The amazing check
        run: |
          exit 1
